#ifndef __WM_USER_H__
#define __WM_USER_H__


#define WM_SETSTABENABLE		WM_USER + 0x0001
#define WM_SETCLASSOBJECTS		WM_USER	+ 0x0002
#define WM_SETRETRIGGERTIME		WM_USER + 0x0003
#define WM_VIDEO_SRC_CHANGED	WM_USER + 0x0004
#define WM_EXPORT_CONFIG		WM_USER + 0x0005
#define WM_IMPORT_CONFIG		WM_USER + 0x0006
#define WM_CONFIG_MODE			WM_USER + 0x0007
#define WM_CONFIG_DIRTY			WM_USER + 0x0008
#define WM_UPDATE_ELEMENT		WM_USER + 0x0009
#define WM_SETUP				WM_USER + 0x000C
#define WM_CONFIG_UPDATED		WM_USER + 0x000D
#define WM_SHOW_WAIT_WND		WM_USER + 0x000E

#endif // __WM_USER_H__

